name: document_detector
description: Flutter plugin cross-platform (iOS, Android) for Combate à Fraude's DocumentDetector (https://github.com/combateafraude).
version: 2.1.2
homepage: https://github.com/combateafraude

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.combateafraude.document_detector
        pluginClass: DocumentDetectorPlugin
      ios:
        pluginClass: DocumentDetectorPlugin
