name: address_check
description: Flutter plugin cross-platform (iOS, Android) for Combate à Fraude's AddressCheck (https://github.com/combateafraude).
version: 1.0.0
author: Combate à Fraude
homepage: https://www.combateafraude.com/

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.combateafraude.address_check
        pluginClass: AddressCheckPlugin
      ios:
        pluginClass: AddressCheckPlugin